go.mod, go.sum, pkg/logger/event/README.md, pkg/logger/event/event.go, pkg/logger/event/event_test.go
https://accelbyte.atlassian.net/browse/IAMP-700
Update plugin to support new log standardization
--by Allen.Li
=> [IAMP-700 Update to support Latest Event Log]

CHANGELOG.md
=> Add CHANGELOG for v2.0.0

pkg/auth/iam/iam.go
fix error message audience validation
Please help me to review : @thoriqsatriya @banukusuma @rjjatson @desniaak @purbopanambang @rafi-isakh
=> AB-718 fix error message audience validation

go.mod, go.sum, pkg/auth/iam/event.go, pkg/auth/iam/iam.go
separate audience and scope validation
=> AB-718 separate aud scope validation

pkg/auth/iam/iam.go
fix error response aud scope validation to comply with oauth 2 standard
=> no-jira fix error response aud scope validation

CHANGELOG.md, go.mod, go.sum, pkg/logger/event/event_test.go, pkg/response/README.md, pkg/response/response.go, pkg/response/response_test.go, pkg/util/README.md, pkg/util/extractor.go, pkg/util/extractor_test.go
- Added response package
- Added ExtractDefault in event package 
@anggorodewanto @thoriqsatriya @fadhillahentino @rjjatson @hvlcrs @yani-satwib
=> no-jira add response package and extract default in event package

go.mod, go.sum, pkg/logger/event/README.md, pkg/response/response.go, pkg/trace/README.md, pkg/trace/trace.go, pkg/trace/trace_test.go, pkg/util/extractor.go
- Add trace pkg
- Update logging event readme for correct extractfunction
- Update response camelCase error response and change WriteErrorString to WriteHeaderAndJson 
- Update extract default util
@anggorodewanto @thoriqsatriya @fadhillahentino @rjjatson @hvlcrs @yani-satwib
=> No jira add trace pkg and update logging, response and util

CHANGELOG.md, pkg/auth/iam/event.go, pkg/auth/iam/iam.go
This PR includes update for Auth Error Response to fit standardize JSON Body of Error Response and minor adjustment on error code field name for matchmaking endpoints
=> SOCP-668 Standardized Error Response for Authentication Process

CHANGELOG.md, pkg/response/response.go, pkg/response/response_test.go
- Add WriteErrorWithEventID in response package
- Update Write in response package
@anggorodewanto @thoriqsatriya @fadhillahentino @hvlcrs
=> Cr-607 Add WriteErrorWithEventID

go.mod, go.sum, pkg/auth/legal/README.md, pkg/auth/legal/event.go, pkg/auth/legal/legal.go
feat: add legal client eligibility filter
=> feat: add legal client eligibility filter

pkg/auth/iam/iam.go
https://accelbyte.atlassian.net/browse/JLT-122
=> feat: Support get token from cookie

go.mod, go.sum, pkg/auth/iam/event.go, pkg/auth/iam/iam.go, pkg/auth/legal/README.md, pkg/auth/legal/event.go, pkg/auth/legal/legal.go
**Changes:**
- feat: Add legal client eligibility filter
- feat: Support get token from cookie
- feat: Referer header checking if token is from cookie
=> feat: JLT-167 remove api gateway

pkg/auth/iam/iam.go
https://accelbyte.atlassian.net/browse/JLT-110
=> fix: Check and get access_token from Authorization header first then Cookie

pkg/auth/iam/README.md, pkg/auth/iam/iam.go, pkg/auth/util/urihelper.go, pkg/auth/util/urihelper_test.go
https://accelbyte.atlassian.net/browse/CORE-3945
=> feat: Support validate referer header by domain only

pkg/auth/iam/iam.go
Ticket: https://accelbyte.atlassian.net/browse/CV-251
UGC service need to have some endpoint to be public endpoint but allow if user send token and service can return appropriate result based on if user is authenticated or not. In this PR, iam filter is added with PublicAuth  method for this kind of endpoint.
=> feat: add public auth filter

go.mod, pkg/auth/iam/event.go, pkg/auth/iam/iam.go
@marselab @angelo-chan @Allen8975701 Please help me review and for the PublicAuth can we return the error token is expired? I see right now if provided with invalid token it will just continue the request
=> feat: adjust token expired error

pkg/auth/iam/iam.go, pkg/constant/constants.go
Note:
- Bearer token used is a player user token
=> chore: add dev stack tracer for insufficient error details

pkg/constant/constants.go, pkg/logger/log/accesslog.go
Add game client and SDK version to log
=> feat: add flightId and game client versions to log

pkg/logger/event/event.go, pkg/logger/event/event_test.go, pkg/util/extractor.go, pkg/util/extractor_test.go
adding flightID to Header for s2s call
=> feat: add flightID to header for s2s (#74)

pkg/auth/iam/iam.go
if user id on the path are the same in the token, check whether the namespaces are the same
=> fix: if user id on the path are the same in the token, check whether the namespaces are the same

pkg/logger/log/README.md, pkg/logger/log/accesslog.go, pkg/logger/log/log.go, pkg/logger/log/maskutil.go, pkg/logger/log/maskutil_test.go
Example:
time=2025-03-19T07:23:13.343Z log_type=access method=GET path="/iam/v3/admin/namespaces/example/users/search?query=wa****@accelbyte.net&startDate=1990-01-01&includeTotal=false" status=200 duration=3850 length=580 source_ip= user_agent="Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/134.0.0.0 Safari/537.36" referer="http://localhost:8080/iam/apidocs/" trace_id=4607d511bdac4d62b506c6f5917f3002 namespace=example user_id=fb45de8225d14b8196bbabce3279e816 client_id=37543083916b463aaa40442736d1d045 request_content_type="" request_body=AB[]AB req_body_size_kb=0.000 response_content_type="application/json" response_body=AB[{"data":[{"authType":"EMAILPASSWD","bans":[],"country":"","createdAt":"2025-03-12T10:50:34.197481+08:00","displayName":"superuse …
=> feat: mask PII information
